export const mockData = [
  {
    doctorName: "Sakthi",
    qualification: "Master",
    experience: "2 years",
    salary: 2000,
  },
  {
    doctorName: "Arun",
    qualification: "PhD",
    experience: "5 years",
    salary: 3000,
  },
  {
    doctorName: "Varun",
    qualification: "Bachelor",
    experience: "3 years",
    salary: 2500,
  },
  {
    doctorName: "Tharun",
    qualification: "Master",
    experience: "4 years",
    salary: 2800,
  },
  {
    doctorName: "Priya",
    qualification: "PhD",
    experience: "7 years",
    salary: 3500,
  },
  {
    doctorName: "Anita",
    qualification: "Bachelor",
    experience: "1 year",
    salary: 2200,
  },
  {
    doctorName: "Raj",
    qualification: "Master",
    experience: "6 years",
    salary: 3200,
  },
  {
    doctorName: "Karthik",
    qualification: "Bachelor",
    experience: "2 years",
    salary: 2300,
  },
  {
    doctorName: "Deepa",
    qualification: "PhD",
    experience: "8 years",
    salary: 3600,
  },
  {
    doctorName: "Vikram",
    qualification: "Master",
    experience: "3 years",
    salary: 2700,
  },
  {
    doctorName: "Lakshmi",
    qualification: "Bachelor",
    experience: "4 years",
    salary: 2400,
  },
  {
    doctorName: "Suresh",
    qualification: "PhD",
    experience: "5 years",
    salary: 3100,
  },
  {
    doctorName: "Mohan",
    qualification: "Master",
    experience: "2 years",
    salary: 2100,
  },
  {
    doctorName: "Ravi",
    qualification: "PhD",
    experience: "6 years",
    salary: 3300,
  },
  {
    doctorName: "Divya",
    qualification: "Bachelor",
    experience: "3 years",
    salary: 2600,
  },
  {
    doctorName: "Meena",
    qualification: "Master",
    experience: "4 years",
    salary: 2900,
  },
  {
    doctorName: "Anil",
    qualification: "PhD",
    experience: "7 years",
    salary: 3400,
  },
  {
    doctorName: "Geeta",
    qualification: "Bachelor",
    experience: "1 year",
    salary: 2100,
  },
  {
    doctorName: "Vijay",
    qualification: "Master",
    experience: "5 years",
    salary: 3100,
  },
  {
    doctorName: "Swati",
    qualification: "PhD",
    experience: "8 years",
    salary: 3700,
  },
  {
    doctorName: "Harish",
    qualification: "Bachelor",
    experience: "2 years",
    salary: 2200,
  },
  {
    doctorName: "Nisha",
    qualification: "Master",
    experience: "3 years",
    salary: 2700,
  },
  {
    doctorName: "Arjun",
    qualification: "PhD",
    experience: "6 years",
    salary: 3200,
  },
  {
    doctorName: "Neha",
    qualification: "Bachelor",
    experience: "4 years",
    salary: 2500,
  },
  {
    doctorName: "Kiran",
    qualification: "Master",
    experience: "2 years",
    salary: 2400,
  },
  {
    doctorName: "Renu",
    qualification: "PhD",
    experience: "7 years",
    salary: 3300,
  },
  {
    doctorName: "Pooja",
    qualification: "Bachelor",
    experience: "3 years",
    salary: 2600,
  },
  {
    doctorName: "Amit",
    qualification: "Master",
    experience: "5 years",
    salary: 3000,
  },
  {
    doctorName: "Sneha",
    qualification: "PhD",
    experience: "4 years",
    salary: 2900,
  },
  {
    doctorName: "Anand",
    qualification: "Bachelor",
    experience: "6 years",
    salary: 2700,
  },
  {
    doctorName: "Rita",
    qualification: "Master",
    experience: "7 years",
    salary: 3200,
  },
  {
    doctorName: "Santosh",
    qualification: "PhD",
    experience: "2 years",
    salary: 2500,
  },
  {
    doctorName: "Jaya",
    qualification: "Bachelor",
    experience: "5 years",
    salary: 2800,
  },
  {
    doctorName: "Dinesh",
    qualification: "Master",
    experience: "3 years",
    salary: 2700,
  },
  {
    doctorName: "Preeti",
    qualification: "PhD",
    experience: "6 years",
    salary: 3100,
  },
  {
    doctorName: "Naveen",
    qualification: "Bachelor",
    experience: "4 years",
    salary: 2600,
  },
  {
    doctorName: "Kavita",
    qualification: "Master",
    experience: "5 years",
    salary: 2900,
  },
  {
    doctorName: "Sandeep",
    qualification: "PhD",
    experience: "3 years",
    salary: 2800,
  },
  {
    doctorName: "Vikas",
    qualification: "Bachelor",
    experience: "2 years",
    salary: 2300,
  },
  {
    doctorName: "Sonia",
    qualification: "Master",
    experience: "6 years",
    salary: 3000,
  },
  {
    doctorName: "Gaurav",
    qualification: "PhD",
    experience: "7 years",
    salary: 3300,
  },
  {
    doctorName: "Shweta",
    qualification: "Bachelor",
    experience: "5 years",
    salary: 2700,
  },
  {
    doctorName: "Manoj",
    qualification: "Master",
    experience: "4 years",
    salary: 2900,
  },
  {
    doctorName: "Ruchi",
    qualification: "PhD",
    experience: "2 years",
    salary: 2200,
  },
  {
    doctorName: "Nitin",
    qualification: "Bachelor",
    experience: "6 years",
    salary: 2800,
  },
  {
    doctorName: "Bhavna",
    qualification: "Master",
    experience: "3 years",
    salary: 2500,
  },
  {
    doctorName: "Ajay",
    qualification: "PhD",
    experience: "7 years",
    salary: 3200,
  },
  {
    doctorName: "Nandini",
    qualification: "Bachelor",
    experience: "4 years",
    salary: 2600,
  },
  {
    doctorName: "Rohan",
    qualification: "Master",
    experience: "5 years",
    salary: 3000,
  },
  {
    doctorName: "Lavanya",
    qualification: "PhD",
    experience: "6 years",
    salary: 3100,
  },
  {
    doctorName: "Ashok",
    qualification: "Bachelor",
    experience: "2 years",
    salary: 2300,
  },
  {
    doctorName: "Shilpa",
    qualification: "Master",
    experience: "3 years",
    salary: 2600,
  },
  {
    doctorName: "Mahesh",
    qualification: "PhD",
    experience: "5 years",
    salary: 2800,
  },
  {
    doctorName: "Sapna",
    qualification: "Bachelor",
    experience: "7 years",
    salary: 2900,
  },
  {
    doctorName: "Vijaya",
    qualification: "Master",
    experience: "4 years",
    salary: 2700,
  },
  {
    doctorName: "Uday",
    qualification: "PhD",
    experience: "3 years",
    salary: 2400,
  },
  {
    doctorName: "Kalyani",
    qualification: "Bachelor",
    experience: "5 years",
    salary: 2600,
  },
];
